name: Compile and run tests.
on: push

jobs:
  build-and-run:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build code
        run: pwd && whoami && ls -l
