name: Tests
on: push

jobs:
  build-and-run:
    name: Build and run tests
    runs-on: ubuntu-latest
    env:
        VYSE_PATH: "/home/runner/work/snap/snap/bin"
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install submodule dependencies 
        run:  git submodule update --init --recursive

      - name: create build scripts
        run:  mkdir bin && cd bin && cmake -G Ninja ..

      - name: Build project and run tests
        run: cd bin && ninja && ctest --rerun-failed --output-on-failure
