name: Compile and run tests.
on: push

jobs:
  build-and-run:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: create build scripts
        run:  mkdir bin && cd bin && cmake -G Ninja ..

      - name: Build project
        run: cd bin && ninja && ./tests
